sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aisha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aisha/react-test npm test

after_success:
  - docker build -t aishaxo/multi-client ./client
  - docker build -t aishaxo/multi-server ./server
  - docker build -t aishaxo/multi-nginx ./nginx
  - docker build -t aishaxo/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  #Push the images to docker hub
  - docker push aishaxo/multi-client
  - docker push aishaxo/multi-server
  - docker push aishaxo/multi-nginx
  - docker push aishaxo/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-926270901348"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY