sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aisha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aisha/react-test npm test

after_success:
  - docker build -t aisha/multi-client ./client
  - docker build -t aisha/multi-server ./server
  - docker build -t aisha/multi-nginx ./nginx
  - docker build -t aisha/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push the images to docker hub
  - docker push aisha/multi-client
  - docker push aisha/multi-server
  - docker push aisha/multi-nginx
  - docker push aisha/multi-worker
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker"
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-east-2-926270901348"
#  bucket_path: "docker"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY